- name: restart nginx
  service:
    name: nginx
    state: restarted

# TODO dynamically generate these handlers
- name: "restart service datapass-backend"
  service:
    name: datapass-backend
    state: restarted

- name: "restart service sidekiq-datapass-backend"
  service:
    name: sidekiq-datapass-backend
    state: restarted
