- name: restart nginx
  service:
    name: nginx
    state: restarted

# TODO dynamically generate these handlers
- name: "restart service datapass-front"
  service:
    name: datapass-front
    state: restarted
- name: "restart service api-auth"
  service:
    name: api-auth
    state: restarted
