- name: Install ruby with rbenv
  include_role:
    name: zzet.rbenv
  vars:
    rbenv:
      env: user
      version: v1.2.0
      default_ruby: 2.7.3
      rubies:
        - version: 2.7.3
    rbenv_owner: "{{ app_user }}"
    rbenv_group: "{{ app_user }}"
    rbenv_users:
      - "{{ app_user }}"
    rbenv_extra_depends:
      - libpq-dev
      - libmagick++-dev
    default_gems_file: "roles/ruby/files/default-gems"
